# 本机配置
Server:
  appName: simple-go-grpc
  Port: 18081

# consul
consul:
  address: 127.0.0.1:8500
  token: 123

# rpc
rpc:
  api-golang: https://domain.com
  arena: 127.0.0.1
  api-server: 127.0.0.1

mysql:
  dsn: username:pwd@tcp(sqlAddress:3306)/brio?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConn: 16
  maxOpenConn: 16
  connMaxLifetime: 600

# redis
redis:
  db: 6
  addr: 127.0.0.1:6379
  password: ''
  readTimeout: 6000
  writeTimeout: 6000

