# fbConsul
fbConsul:
  address: 172.30.3.13:8500
  datacenter: uat

# rpc
rpc:
  api-golang: http://api-golang.service.consul:8080
  arena: http://arena.service.consul:8080

# mysql
mysql:
  dsn: brio:3edc#EDC@tcp(uat1.c2jfdgtlpko2.us-east-2.rds.amazonaws.com:3306)/brio?charset=utf8mb4&parseTime=True&loc=Local
  maxIdleConn: 8
  maxOpenConn: 8
  connMaxLifetime: 3000

# redis
redis:
  db: 6
  addr: uat.naf2fa.ng.0001.use2.cache.amazonaws.com:6380
  password: ''
  readTimeout: 100
  writeTimeout: 100

